### ISSUE TITLE
Issue with React-router 4.1.1

### ISSUE THREAD

**Issue by lineldcosta** [happylinks/blrplt#3]
I am facing issues in app.jsx when i update react-router to the latest version.
ServerRouter is removed from the new version of react-router.
Also is it possible to add old plain routes in this new router? since i am new to react, i couldnt able to grab the things properly. Only this repo seems understandable and working nicely.

**Comment by happylinks** [comment]
Hi lineldcosta,

React-router changed their API a lot when they updated from the alpha to the beta. ServerRouter is StaticRouter now. You can try to check their new documentation and see if you can figure out the changes.
I will also probably update my boilerplate this weekend for this. 
Let me know if you have more questions!

Michiel

**Comment by lineldcosta** [comment]
Hi Michiel,

Thanks for the information. I implemented it. But u r the only sooperman. I could able to understand and implement the server side rendering using your code in my own project.

Thanks

**Comment by lineldcosta** [comment]
I have not implemented AWS, but while pushing to production, i will look into your project again :-)
